name: Tests

on:
  - push
  - pull_request

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1.0.6
        with:
          version: nightly

      - name: Clone repo with submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install dependencies
        run: make

      - name: Show Foundry config
        run: forge config
        
      - name: Run tests
        env:
          ALCHEMY_API_KEY: "${{ secrets.ALCHEMY_API_KEY }}"
        run: make test
